### ISSUE TITLE
targetcli: portal create failed with python errors [powerpc]

### ISSUE THREAD

**Issue by abdhaleegit** [Datera/rtslib#20]
# targetcli
targetcli shell version 2.1.fb41
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/>
/> cd iscsi/iqn.2016-11.com.virttest:emulated-image.target/tpg1/portals
/iscsi/iqn.20.../tpg1/portals> ls
o- portals ............................................................................................................. [0 Portals]

/iscsi/iqn.20.../tpg1/portals> create 0.0.0.0
Using default IP port 3260
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 104, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/node.py", line 1416, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_target.py", line 932, in ui_command_create
    elif ip_address not in utils.list_eth_ips() and not listen_all:
  File "/usr/lib/python2.7/dist-packages/rtslib/utils.py", line 646, in list_eth_ips
    ifaddresses = netifaces.ifaddresses(iface)
ValueError: You must specify a valid interface name.

**Comment by vaibhav92** [comment]
#18 may also fix this error as its gets rid of the list_eth_names entirely. Can you please check if this is the case?
